### ISSUE TITLE
January 2021 Foundation for Public Code community call

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/blog#142]
This call will take place on 21 Jan 2021 at 14.00 UTC. The topic is [About issue #762](https://github.com/publiccodenet/about/issues/762): how do we manage contributions to our open work in practice?

Tasks to complete the call:

- [x] draft agenda
- [x] send invitations and tweet about it
- [x] set up notes document
- [x] have call and take notes
- [ ] write up notes as a blogpost
- [ ] share draft blogpost with call attendees for review
- [ ] publish blogpost!

**Comment by bvhme** [comment]
I'm responding here, since @publiccodenet/about#762 seems more specific than this, being about documenting our work managing contributions.

My take away for things to do myself following this call are:

* Use forks for contributions on our own repositories as well to have the full contributor experience.
* Focus more on the value of contributions, issues and merge requests.
* Everyone in our organization needs to be able to challenge each others ideas as well as be able to have the conversations on the merits and demerits of solutions in the open.
* Whenever there is a 'why' there should be an issue for it.

**Comment by ElenaFdR** [comment]
Here's a [draft blog post](https://hackmd.io/6a4F50DgTwezrbngXab7zw?edit) summarizing this call. I think there's still room to make the discussion summary intro better, but I'd welcome any feedback so far (while I reconnect VS Code to Github).
