### ISSUE TITLE
Tags for blog posts?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/blog#27]
We should probably add something to [the readme](../blob/develop/README.md) about which categories to use. So far we only have posts in the Community call category. I was thinking about writing a blog post about the governance game and are not sure what to use. News? A separate for the game is probably too granular. Having a list to choose from would be easier for the author of a post.

**Comment by Ainali** [comment]
Also, now that we actually have several posts in different categories we should also add the functionality that prints this. There are [some instructions available](https://jekyllrb.com/docs/posts/), but first we need to decide where we want them. Would it fit in the right hand column under "Contribute to this page"?

**Comment by Ainali** [comment]
And to turn it on, I believe we need to add the new functionality to the Jekyll theme (something like categories.liquid) and include it in the proper place. But I'm not sure here.

**Comment by ElenaFdR** [comment]
@lscheske & @nebster, here's the issue for the blog categories. Do you have any categories that you think would be helpful for membership and potential members, or that you anticipate writing blogposts for?

**Comment by lscheske** [comment]
Thanks for flagging this, @ElenaFdR. I have not come across a category list, but based on the blurb at the end of the blog page (...this blog to: share Foundation news; explain what we’re working on; showcase our broader member and contributor community), the published blog-posts, and what I anticipate could be interesting, I think the following categories/tags could be useful (they could be used in combination):

* News
* Updates from our community
* Conferences & events
* Case studies
* Tools
* Standard for Public Code
* Public code
* Good practice

**Comment by ElenaFdR** [comment]
@nebster, @lscheske and I have just discussed creating a permanent link from https://publiccode.net/team/ to blog.publiccode.net/team, so we can always have a path to finding the most recent staff news (for example, [our summer outing](https://blog.publiccode.net/news/2020/08/11/overdue-socially-distant-socializing.html) or [our happy new year post](https://blog.publiccode.net/news/2019/12/20/roll-on-2020.html)). 

This is the first step:

> And to turn it on, I believe we need to add the new functionality to the [Jekyll theme](https://github.com/publiccodenet/jekyll-theme) (something like categories.liquid) and include it in the proper place. But I'm not sure here.

**Comment by ElenaFdR** [comment]
Update: we've decided to go for tags, not categories. 

The difference: categories are hierarchical; tags are non-hierarchical. This means a blogpost can have multiple tags, but not multiple categories. Categories are included in URLs, which can help readers anticipate what they'll read, and help search engines. Both would give us the functionality to create a stable URL linking to all blogposts with that tag or category.

This is because:
- tags give you the flexibility to tag something to multiple buckets (like a codebase name and the activity we carried out to support it)
- tags are easier to change in the future. (We have some guesses now about which buckets we'll want in the future, but we're not sure yet. I propose we start with the ones we have an immediate need for, and then add more as it makes sense. Tags allow you to have quite a lot of flexibility to change the buckets; changing categories in the future will require URL redirects.)
- I don't think most of our audience finds our posts via search engines, so the categories SEO boost isn't our main goal
- Re the category in the URL providing predictability of the link destination, I believe our audience mostly finds our posts via hyperlinks from our other materials, so our hyperlink text and promotional posts should provide that reassurance

**Comment by ElenaFdR** [comment]
So far I've tried following these approaches with no success yet:
- https://blog.webjeda.com/jekyll-categories/ (subbing in tags for categories)
- https://www.jokecamp.com/blog/listing-jekyll-posts-by-tag/

I'm quite sure my understanding of Liquid is the common problem.

**Comment by felixfaassen** [comment]
Here is a hacky but working solution to support tagging in blogposts.

#How does it work?

To a post add the 'tags:' frontmatter variable and choose one or more tags seperated by spaces or comma's.

In the blog post your adding below copy the line:

```Tags: {% for tag in page.tags %} [{{ tag }}](/tags/{{ tag }}/) {% endfor %}

NOTE: Preferably this would be something done in a seperate _layout in the main jekyll theme to avoid duplication of unneeded code (so a layout for blogposts in the base them) including this liquid templating line.


If the tag you add is new you need to add a tagname.md file in the /tags folder. So for example is your tag name "publiccode" there should be a tags/publicode.md file.

The content of that page:
```
---
tag: <insert name of your tag here>
permalink: /tags/<insert the name of your tag here>
---

# {{ page.tag | capitalize }}

{% for post in site.tags[page.tag] %} - {{ post.date | date: "%B %d, %Y" }}: [{{ post.title }}]({{ post.url }})<br>
{% endfor %}
```
